version: "3"
services:
  nginx:
    ports:
      - "3000:80"

  blog-server:
    build:
      context: . #path to dockerfile
      args:
        - NODE_ENV=development #passing argument to build command in dockerfile run command
    volumes:
      - ./:/app #mounting local directory to docker container for live reload, file sync
      - /app/node_modules
    environment:
      - NODE_ENV=development #setting environment variable if required
    command: npm run dev #override default command given in Dockerfile
