#for all environments
version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # mount the nginx config file to the container , left side is the path to the file on the host machine and right side is the default path to the file in the container, right is where nginx looks for the config file
    depends_on:
      - blog-server

  blog-server:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-data:/data/db # named volume to persist data, /data/db is the default data directory for mongo acc to docs
    env_file:
      - ./.env # mongo requires a username and password to be set as env variables with specific env var names for authentication see docs

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-db-data:
